Repository didierganthier/space-travellers-hub, pull requests merged in 2022-11, with the labels that each got.

#66 Create basic application
  .babelrc
  .eslintrc.json
  .github/workflows/linters.yml
  .gitignore
  .stylelintrc.json
  MIT.md
  README.md
  app_screenshot.png
  package-lock.json
  package.json
  postcss.config.js
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.js
  src/App.test.js
  src/app/store.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
  tailwind.config.js
Labels: dependencies

#67 Routing sections
  package-lock.json
  src/App.js
  src/components/Navbar.js
  src/components/Profile.js
  src/index.js
Labels: routing, components

#69 Basic mission structure
  src/App.js
  src/App.test.js
  src/__snapshots__/App.test.js.snap
  src/components/Navbar.js
  src/pages/Missions.js
  src/pages/Profile.js
  src/redux/initialState.js
Labels: setup

#72 Create Rocket page, fetch Rocket data
  src/App.js
  src/App.test.js
  src/__snapshots__/App.test.js.snap
  src/pages/Missions.js
  src/pages/Rockets.js
  src/redux/configureStore.js
  src/redux/rockets/rocketsSlice.js
  src/services/fetchRockets.js
Labels: redux, routing, api, components

#73 Filter joined missions
  public/favicon.ico
  src/pages/Missions.js
  src/pages/Profile.js
Labels: redux, api, components

#75 Display Active Rockets in Profile
  src/pages/Profile.js
Labels: components

#77 Refactor project
  .babelrc
  .eslintrc.json
  .github/workflows/linters.yml
  .gitignore
  .stylelintrc.json
  MIT.md
  README.md
  app_screenshot.png
  package-lock.json
  package.json
  postcss.config.js
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.js
  src/__snapshots__/App.test.js.snap
  src/app/store.js
  src/assets/elon.png
  src/components/Navbar.js
  src/components/NotFound.js
  src/index.css
  src/index.js
  src/logo.svg
  src/pages/Missions.js
  src/pages/Profile.js
  src/pages/Rockets.js
  src/redux/configureStore.js
  src/redux/missions/missionSlice.js
  src/redux/rockets/rocketsSlice.js
  src/reportWebVitals.js
  src/services/fetchMissions.js
  src/services/fetchRockets.js
  src/services/testWrapper.js
  src/setupTests.js
  src/tests/App.test.js
  src/tests/Missions.test.js
  src/tests/Rockets.test.js
  src/tests/__snapshots__/App.test.js.snap
  src/tests/__snapshots__/Missions.test.js.snap
  tailwind.config.js
Labels: redux, api, ui, components, tests
